backend:
  name: git-gateway
  branch: master
media_folder: 'public/assets'
public_folder: '/assets'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'src/blog'
    create: false
    fields:
      - { label: 'Course', name: 'course', widget: 'string' }
      - { label: 'Course Handler', name: 'courseHandler', widget: 'string' }
      - { label: 'Course Handler Info', name: 'courseHandlerInfo', widget: 'string' }
      - { label: 'Course Handler Email', name: 'courseHandlerEmail', widget: 'string' }
      - { label: 'Course Outcomes', name: 'courseOutcomes', widget: 'markdown' }
